// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9q0_JpbbQVYXIb720gf5NHbYSsnpkzR0',
    appId: '1:991993497474:web:934eabfd8c2a972d18719b',
    messagingSenderId: '991993497474',
    projectId: 'crudcode-3520e',
    authDomain: 'crudcode-3520e.firebaseapp.com',
    storageBucket: 'crudcode-3520e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQDr6MP9fKJ4_3Vsy0_z5Q62I0yGDMnnw',
    appId: '1:991993497474:android:990a5b8930a520b318719b',
    messagingSenderId: '991993497474',
    projectId: 'crudcode-3520e',
    storageBucket: 'crudcode-3520e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnueoIwnWuzohLxExsrDkrW978F8FEXQk',
    appId: '1:991993497474:ios:7d068399196791da18719b',
    messagingSenderId: '991993497474',
    projectId: 'crudcode-3520e',
    storageBucket: 'crudcode-3520e.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnueoIwnWuzohLxExsrDkrW978F8FEXQk',
    appId: '1:991993497474:ios:12c486b7578ac91f18719b',
    messagingSenderId: '991993497474',
    projectId: 'crudcode-3520e',
    storageBucket: 'crudcode-3520e.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
